image: galtspace/node-test-runner:0.5.13

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

test_async:
  stage: test
  script:
   - npm install
   - make lint && make compile && make test
  tags:
    - docker
